# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1duP9fSw1kw590eHejpApBIwg48QCCm
"""

#!pip install -q streamlit

import streamlit as st

st.title("My first webapp")
st.header("APP")
st.subheader("I like python")
st.write("Haha")
st.markdown("haha")
